name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build

    # Optionally, deploy to a service like Heroku, AWS, etc.
    # - name: Deploy
    #   run: your deployment script or command here
    #   env:
    #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

